blueprint:
  name: Danfoss Ally External Window Open/Close
  description: Turn On/Off Heating on Danfoss Ally based on external Window Sensor.
  domain: automation
  source_url: https://github.com/gjelsoe/HA_Blueprints/blob/main/Danfos_Ally/Danfoss_Ally_External_Window_Open_Close.yaml
  input:
    onoff_wait_delay:
      name: Wait Delay
      description: The amount of time to wait before the Door/Window is consider Open or Closed.
      default: '00:10:00'
      selector:
        duration:
    window_sensor:
      name: Window Sensor
      description: This sensor will turn On/Off target eTRV.
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    etrv_target:
      name: eTRV
      description: Danfoss Ally eTRV to be controlled.
      selector:
        device:
          manufacturer: Danfoss
          entity:
            domain: climate
variables:
  device: !input etrv_target
  ieee: "{{(device_attr(device, 'identifiers')|list)[0][1]}}"
  window_device: !input window_sensor

trigger:
  - type: opened
    platform: device
    device_id: '{{ device_id(window_device) }}'
    entity_id: !input window_sensor
    domain: binary_sensor
    for: !input onoff_wait_delay
  - type: not_opened
    platform: device
    device_id: '{{ device_id(window_device) }}'
    entity_id: !input window_sensor
    domain: binary_sensor
    for: !input onoff_wait_delay
condition: []
action:
  - if:
      - type: is_open
        condition: device
        device_id: '{{ device_id(window_device) }}'
        entity_id: !input window_sensor
        domain: binary_sensor
    then:
      - service: zha.set_zigbee_cluster_attribute
        data:
          cluster_type: in
          ieee: '{{ ieee }}'
          endpoint_id: 1
          cluster_id: 513
          attribute: 16387
          value: "1"
          manufacturer: "4678"
  - if:
      - type: is_not_open
        condition: device
        device_id: '{{ device_id(window_device) }}'
        entity_id: !input window_sensor
        domain: binary_sensor
    then:
      - service: zha.set_zigbee_cluster_attribute
        data:
          cluster_type: in
          ieee: '{{ ieee }}'
          endpoint_id: 1
          cluster_id: 513
          attribute: 16387
          value: "0"
          manufacturer: "4678"
mode: single
