blueprint:
  name: Danfoss Ally External Window Open/Close
  description: Turn On/Off Heating on Danfoss Ally based on external Window Sensor.
  domain: automation
  input:
    window_sensor:
      name: Window Sensor
      description: This sensor will turn On/Off target eTRV.
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    etrv_target:
      name: eTRV
      description: The eTRV valve to be controlled.
      selector:
        target:
          entity:
            domain: climate

trigger_variables:
  sensor_device: !input window_sensor
  sensor_id: "{{ device_id(sensor_device) }}"
  device: !input etrv_target
  etrv_ieee: "{{ (device_attr(device, 'identifiers')|list)[0][1] }}"

trigger:
  - type: opened
    platform: device
    device_id: "{{ sensor_id }}"
    entity_id: !input window_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - type: not_opened
    platform: device
    device_id: "{{ sensor_id }}"
    entity_id: !input window_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - if:
      - type: is_open
        condition: device
        device_id: "{{ sensor_id }}"
        entity_id: !input window_sensor
        domain: binary_sensor
    then:
      - service: zha.set_zigbee_cluster_attribute
        data:
          cluster_type: in
          ieee: "{{ etrv_ieee }}"
          endpoint_id: 1
          cluster_id: 513
          attribute: 16387
          value: "1"
          manufacturer: "4678"
  - if:
      - type: is_not_open
        condition: device
        device_id: "{{ sensor_id }}"
        entity_id: !input window_sensor
        domain: binary_sensor
    then:
      - service: zha.set_zigbee_cluster_attribute
        data:
          cluster_type: in
          ieee: "{{ etrv_ieee }}"
          endpoint_id: 1
          cluster_id: 513
          attribute: 16387
          value: "0"
          manufacturer: "4678"
mode: single
